name: 'Updates a Relay workflow on commit'
description: 'This action will update a named Relay workflow from GitHub'
inputs:
  relay_api_token:
    required: true
    description: "Relay API token"
  relay_workflow:
    required: false
    description: "Relay workflow name"
  relay_workflow_file:
    required: false
    description: "Relay workflow file"
  relay_configuration_file:
    required: false
    description: "Relay CLI configuration file"
  relay_configuration_context:
    required: false
    description: "Relay CLI configuration context"
  relay_configuration_debug:
    required: false
    description: "Relay CLI configuration debug"
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'link-2'
  color: 'purple'
